apiVersion: feast.dev/v1alpha1
kind: FeatureStore
metadata:
  name: sample-oidc-auth
spec:
  feastProject: my_project
  services:
    onlineStore:
      image: quay.io/dmartino/feature-server:0.3
      persistence:
        file:
          path: /data/online_store.db
    offlineStore:
      image: quay.io/dmartino/feature-server:0.3
      persistence:
        file:
          type: dask
    registry:
      local:
        image: quay.io/dmartino/feature-server:0.3
        persistence:
          file:
            path: /data/registry.db
  authz:
    oidc:
      secretRef:
        name: oidc-secret
---
kind: Secret
apiVersion: v1
metadata:
  name: oidc-secret
stringData:
  client_id: client_id
  auth_discovery_url: auth_discovery_url
  client_secret: client_secret
  username: username
  password: password
