apiVersion: v1
kind: ServiceAccount
metadata:
  name: feast-sa
  namespace: feast-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: feast-role
  namespace: feast-dev
rules:
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: feast-rolebinding
  namespace: feast-dev
subjects:
  - kind: ServiceAccount
    name: feast-sa
    namespace: feast-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: feast-role
